In [11]:
import numpy as np


In [12]:
#sigmoid function
def nonlin(x, deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [13]:
#initialize input
x=np.array([[0,0,1], [0,1,1], [1,0,1],[1,1,1]])


In [14]:
#initialize output 
y=np.array([0,0,1,1]).T  #.T transpozes it so it becomes a single column
#initialize the seed
np.random.seed(1)

In [15]:
#initializee the weights
w0=2*np.random.random((3,1))-1
#check the values
w0 

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [16]:
for iter in range (100):
    l0=x
    l1=np.dot(l0,w0)  #l1 is the predicted y which  has error
    l1=nonlin(l1)
    l1_error=y-l1   #to find the error
    #to backpropagate the error
    delta_l1=l1_error*nonlin(l1,True)
    #update the weights
    w0=w0+np.dot(l0.T,delta_l1)
print("end of training.view the output")
print(l1)

end of training.view the output
[[0.05194868 0.05194868 0.93041804 0.93041804]
 [0.03375157 0.03375157 0.98024587 0.98024587]
 [0.02516258 0.02516258 0.97319054 0.97319054]
 [0.01618816 0.01618816 0.99263144 0.99263144]]
